rpc_request_timeout: 30

consumers:
  some_consumer:
    class_name: MyConsumer
    rpc: false
    pool_size: 1
    exchange:
      name: "consumer_exchange"
      type: "fanout"
      opts:
        durable: false
    queue:
      name: "consumer_queue"
      opts:
        durable: false
        
  some_rpc:
    class_name: MyRPC
    rpc: true
    pool_size: 1
    exchange:
      name: "rpc_exchange"
      type: "fanout"
      opts:
        durable: false
    queue:
      name: "rpc_queue"
      opts:
        durable: false
  
publishers:
  some_publisher:
    exchange:
      name: "consumer_exchange"
      type: "fanout"
      opts:
        durable: false
  rpc_publisher:
    exchange:
      name: "rpc_exchange"
      type: "fanout"
      opts:
        durable: false