rpc_request_timeout: 10

consumers:
  some_consumer:
    class_name: MyConsumer
    rpc: false
    pool_size: 1
    exchange:
      name: "consumer_exchange"
      type: "fanout"
      opts:
        durable: true
    queue:
      name: "consumer_queue"
      opts:
        durable: true
        
  some_rpc:
    class_name: MyRPC
    rpc: true
    pool_size: 1
    exchange:
      name: "rpc_exchange"
      type: "direct"
      opts:
        durable: true
    queue:
      name: "rpc_queue"
      opts:
        durable: true
  
publishers:
  some_publisher:
    exchange:
      name: "exchange_name"
      type: "direct"
      opts:
        durable: true