development:
  default:
    :host: localhost
    :port: 5672
    :user: guest
    :pass: guest
    :vhost: /
    :threaded: true
    :heartbeat: 2
  rpc:
    :host: localhost
    :port: 5672
    :user: guest
    :pass: guest
    :vhost: /
    :threaded: true
    :heartbeat: 2

test:
  default:
    :host: localhost
    :port: 5672
    :user: guest
    :pass: guest
    :vhost: /
    :threaded: true
    :heartbeat: 2
  rpc:
    :host: localhost
    :port: 5672
    :user: guest
    :pass: guest
    :vhost: /
    :threaded: true
    :heartbeat: 2
